""" Preset courses. """

COURSES = {
    'avenuecorsopaseo':                 ('abcdefghijklmnopqrstu', 0),
    'ballonscentrale':                  ('AnLHgceqtrMBoipjDFkSu', 180),
    'rondevanwevelgem':                 ('abcmgfteqonLPjkIDHrSu', 0),
    'lahautmontagne':                   ('abcfimetKGLHJsdopRQNU', 0),
    'firenzemilano':                    ('abcgiDHqntmKOLrepJsfu', 0),
    'laclassicissima':                  ('AebQRNHPcgikDFsLojmtu', 90),

    "classiquedavril":                  ('AbJiLcGHtdfpkmnrqEoSu', 90),
    'sprintdemontagne':                 ('afCOLibNDPSgTkerjQHmu', 180),

    # 'vittellaplanchedesbellesfilles':   ('aIHdTFljsMNPBCORKGQEU', 225),
    'laplanchedesbellesfilles':         ('aIHdTFljsMNPBCORKGQEU', 225),
    # 'dolestationdesrousses':            ('ajfMECTKsqRLPHiDBNOgu', 135),
    'stationdesrousses':                ('ajfMECTKsqRLPHiDBNOgu', 135),
    # 'nantuachambery':                   ('aNPHtimOELKRBSJCQDFgu', 0),
    'chambery':                         ('aNPHtimOELKRBSJCQDFgu', 0),
    # 'paupeyragudes':                    ('atsmCJdifNBERKOLPHGQU', 0),
    # 'paupayragudes':                    ('atsmCJdifNBERKOLPHGQU', 0),
    'peyragudes':                       ('atsmCJdifNBERKOLPHGQU', 0),
    # 'payragudes':                       ('atsmCJdifNBERKOLPHGQU', 0),
    # 'saintgironsfoix':                  ('alktJCRPMEHFSqGOBidnu', 0),
    'foix':                             ('alktJCRPMEHFSqGOBidnu', 0),
    # 'laissacseveraclegliselepuyenvelay':('AsNLcITmrQOkJPFGEDHBu', 45),
    'lepuyenvelay':                     ('AsNLcITmrQOkJPFGEDHBu', 45),
    # 'lamureserrechevalier':             ('aICEtQGORLPHJMNKDBSu', 0),
    'serrechevalier':                   ('aICEtQGORLPHJMNKDBSu', 0),
    # 'brianconizoard':                   ('afiPmTKSdjoCQRLHBNGEU', 0),
    'izoard':                           ('afiPmTKSdjoCQRLHBNGEU', 0),

    'histoiredunalleretretour':         ('aCLBImPHjkdfoestrQGNU', 180),
    'coldasger':                        ('acPHFBljIdKQRsmtGEONU', 315),
    'legrandbaroud':                    ('abjoNDHPmiRLFtGKQEscu', 180),
    'ladoyenne':                        ('ALeCFOKBnjpdMHitSqRGU', 90),
    'lentrecotes':                      ('adeNibjpOKRLtCFSqMhu', 0),
    'colcintre':                        ('anJtDBshIOKPFGRLmeqcu', 0),
    'colhector':                        ('ashbMODPJTIKLFQERGCNU', 0),
    'piegepoursprinteurs':              ('aLtqDPHBJiFkromneScgu', 0),

    'teamtrial':                        ('arJbcSeqLophtinu', 135),

    'stage7':                           ('aw3gMRPkeqos4cDHjTniu', 0),
    'stage8':                           ('awh4oIcQDF3prsejLktgu', 0),
    'stage9':                           ('Aw3p5Wokjq4e8VhgirsTu', 180),
    'stage11':                          ('aw8zqgirxysopthk7VeJu', 0),
    'stage12':                          ('Aw4qMOKRFsd3ptnhgeTju', 202.5),
    'stage18':                          ('awh4Lopc5Vr3gqJksteIU', 157.5),

    '2018.1':                           ('AbcdIjfltQHRPgkSmnoeu', 0),
    '2018.2':                           ('AIfmonjldbcHEPGktrqsu', 90),
    '2018.3':                           ('abcPOdlImEHTJnfRSqgku', 0),
    '2018.4':                           ('abKcdsHpeIGJflrmnoqTu', 337.5),
    '2018.5':                           ('aijRlnPOQcFdMBgestkHU', 0),
    '2018.6':                           ('almniSTboJkHdEqGPRFCu', 0),
    '2018.7':                           ('aegrqHOtspKbcdfiJlmnu', 90),
    '2018.8':                           ('abcdHigtQSflmponekrJu', 0),
    '2018.9':                           ('ag6nJl58iyehWTxprsqu', 180),
    '2018.10':                          ('aBcmigstqrjeNLODPHFku', 180),
    '2018.11':                          ('AdMEGPfLHBjIStqcRNkou', 0),
    '2018.12':                          ('adCLPJBHFimorTsKNQEgu', 0),
    '2018.13':                          ('abegQcStdKfijPlrHmonu', 90),
    '2018.14':                          ('AiKbdEGPQHLFrmonTJsCu', 0),
    '2018.15':                          ('acdstRKOIgqHjPBflemnu', 0),
    '2018.16':                          ('aiKEFCLBgJmntrqoDPHSu', 135),
    '2018.17':                          ('ACNsFBiMLPHtgEDOQU', 0),
    '2018.18':                          ('abcdfEIlSTHqmJkRnPgou', 0),
    '2018.19':                          ('asmTnrkECPijDoqLBHgFu', 225),
    '2018.20':                          ('AGfIkntBSRdhqJcpomeLU', 0),
    '2018.21':                          ('v2opciJx56Xsghterbu', 180),

    '2019.1':                           ('v2hkELjMFs9qI6zrGntu', 0),
    '2019.2':                           ('adGHkmQPJtnrEFSIou', 270),
    '2019.3':                           ('12ltjsI3nd9omEFQPCHu', 0),
    '2019.4':                           ('12rJfehS9Tnlg3qimpobu', 135),
    '2019.5':                           ('12DPmtJ3sqrnIEKHBgOL+u', 180),
    '2019.6':                           ('v2KEGLHji4qCODPBs9N-U', 0),
    '2019.7':                           ('12sET3qo8zrkI4PHbdjlu', 180),
    '2019.8':                           ('12MBIEK+sFjOLgqDPHntu', 180),
    '2019.9':                           ('12iKNOQmJ9tHPBsDFgeLu', 225),
    '2019.10':                          ('12orptd9HFjIS5W3ge8yu', 180),
    '2019.11':                          ('v2niRJHl7zqop3ksYeTmu', 0),
    '2019.12':                          ('12nIt9jocS3MRKPBEGDHFu', 180),
    '2019.13':                          ('ahlQmPJCFktngeu', 0),
    '2019.14':                          ('12bsi3JROELFkPHTMGQNU', 0),
    '2019.15':                          ('v2m9sjCDHFPEGKLBIoR-QU', 180),
    '2019.16':                          ('12RPtms3iqLhfkengYJu', 180),
    '2019.17':                          ('12tCsiJ3qmohfenRKDBu', 0),
    '2019.18':                          ('v2itCEGBkMDHPjoNRQLFu', 225),
    '2019.19':                          ('v2tisCPJbE9NOLFgHqMKRU', 270),
    '2019.20':                          ('12sCOLPFi9QDHBJKN-EGU', 180),
    '2019.21':                          ('v2eg6W3khfPnOmisru', 0),
}


LONG_STAGES = {
    'stage7+':                          ('v23gMRPkeqos4cDHjTYniu', 0),
    'stage8+':                          ('v2h4oIcQDF3prsejLktgYu', 0),
    'stage9+':                          ('12Y3p5Wokjq4e8VhgirsTu', 180),
    'stage11+':                         ('v28zqgir9xysopthk7VeJu', 0),
    'stage12+':                         ('124qMOKRFsd3ptnYhgeTju', 202.5),
    'stage18+':                         ('v2h4YLopc5Vr3gqJksteIU', 157.5)
}


DUPLICATE_NAMES = dict(
    lecolduballon='ballonscentrale',
    vatternrundan='piegepoursprinteurs',
    styrkeproven='legrandbaroud',
    plateauxdewallonie='classiquedavril',
    vuokatinvaara='coldasger',
    etapedelavallee='histoiredunalleretretour',

    vaetternrundan='piegepoursprinteurs',
    styrkeproeven='legrandbaroud',
    vittellaplanchedesbellesfilles='laplanchedesbellesfilles',
    dolestationdesrousses='stationdesrousses',
    nantuachambery='chambery',
    paupeyragudes='peyragudes',
    paupayragudes='peyragudes',
    payragudes='peyragudes',
    saintgironsfoix='foix',
    laissacseveraclegliselepuyenvelay='lepuyenvelay',
    lamureserrechevalier='serrechevalier',
    brianconizoard='izoard'
)
