""" Preset courses. """

COURSES = {
    'avenuecorsopaseo':                 ('abcdefghijklmnopqrstu', 0),
    'ballonscentrale':                  ('AnLHgceqtrMBoipjDFkSu', 180),
    'lecolduballon':                    ('AnLHgceqtrMBoipjDFkSu', 180),
    'rondevanwevelgem':                 ('abcmgfteqonLPjkIDHrSu', 0),
    'lahautmontagne':                   ('abcfimetKGLHJsdopRQNU', 0),
    'firenzemilano':                    ('abcgiDHqntmKOLrepJsfu', 0),
    'laclassicissima':                  ('AebQRNHPcgikDFsLojmtu', 90),

    "classiquedavril":                  ('AbJiLcGHtdfpkmnrqEoSu', 90),
    'sprintdemontagne':                 ('afCOLibNDPSgTkerjQHmu', 180),

    'vittellaplanchedesbellesfilles':   ('aIHdTFljsMNPBCORKGQEU', 225),
    'laplanchedesbellesfilles':         ('aIHdTFljsMNPBCORKGQEU', 225),
    'dolestationdesrousses':            ('ajfMECTKsqRLPHiDBNOgu', 135),
    'stationdesrousses':                ('ajfMECTKsqRLPHiDBNOgu', 135),
    'nantuachambery':                   ('aNPHtimOELKRBSJCQDFgu', 0),
    'chambery':                         ('aNPHtimOELKRBSJCQDFgu', 0),
    'paupeyragudes':                    ('atsmCJdifNBERKOLPHGQU', 0),
    'paupayragudes':                    ('atsmCJdifNBERKOLPHGQU', 0),
    'peyragudes':                       ('atsmCJdifNBERKOLPHGQU', 0),
    'payragudes':                       ('atsmCJdifNBERKOLPHGQU', 0),
    'saintgironsfoix':                  ('alktJCRPMEHFSqGOBidnu', 0),
    'foix':                             ('alktJCRPMEHFSqGOBidnu', 0),
    'laissacseveraclegliselepuyenvelay':('AsNLcITmrQOkJPFGEDHBu', 45),
    'lepuyenvelay':                     ('AsNLcITmrQOkJPFGEDHBu', 45),
    'lamureserrechevalier':             ('aICEtQGORLPHJMNKDBSu', 0),
    'serrechevalier':                   ('aICEtQGORLPHJMNKDBSu', 0),
    'brianconizoard':                   ('afiPmTKSdjoCQRLHBNGEU', 0),
    'izoard':                           ('afiPmTKSdjoCQRLHBNGEU', 0),

    'histoiredunalleretretour':         ('aCLBImPHjkdfoestrQGNU', 180),
    'coldasger':                        ('acPHFBljIdKQRsmtGEONU', 315),
    'legrandbaroud':                    ('abjoNDHPmiRLFtGKQEscu', 180),
    'ladoyenne':                        ('ALeCFOKBnjpdMHitSqRGU', 90),
    'lentrecotes':                      ('adeNibjpOKRLtCFSqMhu', 0),
    'colcintre':                        ('anJtDBshIOKPFGRLmeqcu', 0),
    'colhector':                        ('ashbMODPJTIKLFQERGCNU', 0),
    'piegepoursprinteurs':              ('aLtqDPHBJiFkromneScgu', 0),

    'stage7':                           ('aw3gMRPkeqos4cDHjTniu', 0),
    'stage8':                           ('awh4oIcQDF3prsejLktgu', 0),
    'stage9':                           ('Aw3p5Wokjq4e8VhgirsTu', 180),
    'stage11':                          ('aw8zqgirxysopthk7VeJu', 0),
    'stage12':                          ('Aw4qMOKRFsd3ptnhgeTju', 202.5),
    'stage18':                          ('awh4Lopc5Vr3gqJksteIU', 157.5),

    'stage7+':                          ('v23gMRPkeqos4cDHjTYniu', 0),
    'stage8+':                          ('v2h4oIcQDF3prsejLktgYu', 0),
    'stage9+':                          ('12Y3p5Wokjq4e8VhgirsTu', 180),
    'stage11+':                         ('v28zqgir9xysopthk7VeJu', 0),
    'stage12+':                         ('124qMOKRFsd3ptnYhgeTju', 202.5),
    'stage18+':                         ('v2h4YLopc5Vr3gqJksteIU', 157.5),
}
